### ISSUE TITLE
2.8 compatibility?

### ISSUE THREAD

**Issue by Michaelknubben** [leukbaars/BRM-UVTools#6]
Hey Bram, 

Any chance you're still using this, and you'd share your updated code?
There's an alternative in Magic UV but I prefer the way this one functions!

**Comment by motorsep** [comment]
+100

I'd too love for this add-on to be updated for Blender 2.80

**Comment by Michaelknubben** [comment]
He's since posted a bunch about an updated version for 2.8 on Twitter, so it's coming: https://twitter.com/Leukbaars/status/1175315774396760064
